### ISSUE TITLE
How to use dns.c do dns redirecting ?

### ISSUE THREAD

**Issue by Pillar1989** [wahern/dns#18]
Hi,
    I want to use dns.c as my raspberry pi dns server, when  the raspberry pi is offline , all of dns request will be redirected a IP which I pointed. 
   now I use dnsmasq to do this function, I set "address=/#/172.1.8.1" on dnsmasq.conf. But I dont like dnsmasq.  so how can I use dns.c do same job ?

**Comment by wahern** [comment]
dns.c is a low-level DNS library, not a standalone application or service. To replace dnsmasq you'd basically need to reimplement all of it (directly or by using other libraries), except the DNS portions.

**Comment by wahern** [comment]
Contact me by e-mail if you have more questions along those lines. I might be able to share some code for implementing a DNS server.

**Comment by X25guru** [comment]
is there a page with basic use? I just have a bunch of IPs and need to do the equivalent of gethostbyaddr() on them.
